modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="itemfusion"
version="0.2.0"
displayName="ItemFusion"
description='''Fusion table: combine vanilla items into new ones. Recipes are data-driven JSON.'''
authors="T & Adam"

[[dependencies.itemfusion]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemfusion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
